# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracks" do
  name "tracks"
  desc "A batteries included toolkit for hypermedia servers"
  homepage "https://tracks.anomalousventures.com"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracks"

  on_macos do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_x86_64.tar.gz"
      sha256 "bd3fe0edb544ea63442d3644205595134ec7d3e17506c8ff8d2aa8b2b6a78d39"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_arm64.tar.gz"
      sha256 "904bbada066e76a48cab6438ef176fb74f6a70f5220161c46ca41df261bcb86c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_x86_64.tar.gz"
      sha256 "ce5592b3996dc802506f0581d741f76dbb9f4185c07058da2852a931ea6b2806"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_arm64.tar.gz"
      sha256 "9e0f31fcfb8ef4955a680313fcf3e42a1dac9015979d7a33913a00912edcbc67"
    end
  end

  # No zap stanza required
end
