# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracks" do
  name "tracks"
  desc "A batteries included toolkit for hypermedia servers"
  homepage "https://tracks.anomalousventures.com"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracks"

  on_macos do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b0f83a5e8e7e37a7ead24617848e769a01ec1f8198548e39eca973bbf38f16c9"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_arm64.tar.gz"
      sha256 "f9725d7a07318df0c18ce8a085d39fa46e94373adb9902124c4b9a6002370198"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_x86_64.tar.gz"
      sha256 "aa7ecddca43f00897399746bfc03a8f522ef29454470e7adc23ff56a7055e3c7"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_arm64.tar.gz"
      sha256 "2274a3e7005a9047787ed57bfb6c14d8c097be3ad5593a1b5015bc280303670d"
    end
  end

  # No zap stanza required
end
