# This file was generated by GoReleaser. DO NOT EDIT.
cask "tracks" do
  name "tracks"
  desc "A batteries included toolkit for hypermedia servers"
  homepage "https://tracks.anomalousventures.com"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tracks"

  on_macos do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_x86_64.tar.gz"
      sha256 "5625d5dbc3ae8dbb18d2196891787d299effadf79b9929534ed06bafc34af2ba"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Darwin_arm64.tar.gz"
      sha256 "128266e102c819cab5197c13808724e74ccfbabd698fa85f4f0336253596af80"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_x86_64.tar.gz"
      sha256 "434824c565132320074d9bea5a69ca83e55c0b8c0ac213d4262905fab4b081ac"
    end
    on_arm do
      url "https://github.com/anomalousventures/tracks/releases/download/v#{version}/tracks_#{version}_Linux_arm64.tar.gz"
      sha256 "b60ec18ab308a0ed927d71effaed9abb79a40fbe3d8b7ea64b2b2b1e50d54e29"
    end
  end

  # No zap stanza required
end
